package edu.ap.takeexamapp.navigation

object AppRoute {
    const val HOME = "home"
    const val TAKE_EXAM = "take_exam"
    const val SELECT_STUDENT = "select_student/{examId}"
    const val CONFIRM_LOCATION = "confirm_location/{examId}/{userId}"
    const val EXAM_SESSION = "exam_session"
    const val SUBMISSION_RECEIPT = "submission_receipt/{attemptId}"
    const val ADMIN_LOGIN = "admin_login"
    const val ADMIN_DASHBOARD = "admin_dashboard"
    const val MANAGE_USERS = "manage_users"
    const val MANAGE_EXAMS = "manage_exams"
    const val EDIT_EXAM = "edit_exam/{examId}"
    const val RESULTS_HUB = "results_hub"
    const val PENDING_RESULTS = "pending_results"
    const val GRADE_ATTEMPT = "grade_attempt/{attemptId}"
    const val RESULT_USERS = "result_users"
    const val USER_ATTEMPTS = "user_attempts/{userId}"
    const val RESULT_EXAMS = "result_exams"
    const val EXAM_ATTEMPTS = "exam_attempts/{examId}"
    const val RESULT_DETAIL = "result_detail/{attemptId}"

    fun editExam(examId: String) = "edit_exam/$examId"
    fun selectStudent(examId: String) = "select_student/$examId"
    fun confirmLocation(examId: String, userId: String) = "confirm_location/$examId/$userId"
    fun submissionReceipt(attemptId: String) = "submission_receipt/$attemptId"
    fun gradeAttempt(attemptId: String) = "grade_attempt/$attemptId"
    fun userAttempts(userId: String) = "user_attempts/$userId"
    fun examAttempts(examId: String) = "exam_attempts/$examId"
    fun resultDetail(attemptId: String) = "result_detail/$attemptId"
}
